* What FifthXenia is.
- FifthXenia is a non-profit, that focuses on developing solutions that benefit humanity. 
  - We build systems that buttress decentralization over centralization, non-violent cooperation over violent force, transparency over secrecy, truth and honesty over lies and deception, encryption and anonymity over big brother, sound economics, spines over spineless, simplicitly and just enough over heedless extraneous addiction, and liberty over death.
  - (leading from the front, just people, same rules and principles applying to everyone) A society of autonomous individuals lifting those beneath them and building up, rather than  (leading from the back, ruler not same as ruled, lies, special privileges) top down stagnated slavery trauma poison.

-----

-----


#+begin_quote
An invisible empire has been set up above the forms of democracy.

Since I entered politics, I have chiefly had men’s views confided to me privately. Some of the biggest men in the United States, in the field of commerce and manufacture, are afraid of somebody, are afraid of something. They know that there is a power somewhere so organized, so subtle, so watchful, so interlocked, so complete, so pervasive, that they had better not speak above their breath when they speak in condemnation of it.

...[the] middle class is being more and more squeezed out by the processes which we have been taught to call processes of prosperity. Its members are sharing prosperity, no doubt; but what alarms me is that they are not originating prosperity. No country can afford to have its prosperity originated by a small controlling class. 


All over the Union people are coming to feel that they have no control over the course of affairs.

Men said: “We vote; we are offered the platform we want; we elect the men who stand on that platform, and we get absolutely nothing.” So they began to ask: “What is the use of voting? We know that the machines of both parties are subsidized by the same persons, and therefore it is useless to turn in either direction.”
#+end_quote
- President Woodrow Wilson, Excerpts from [[https://teachingamericanhistory.org/document/the-new-freedom][The New Freedom]], 1913
  - Pre-[[https://en.wikipedia.org/wiki/Transistor][transistor]] and digital age, radio, tv, pre the decision of the U.S to engage in [[https://en.wikipedia.org/wiki/Full-spectrum_dominance][full spectrum warfare]] post dieing down of the cold war, post [[https://en.wikipedia.org/wiki/Aurora,_Texas,_UFO_incident][Aurora]], pre [[https://en.wikipedia.org/wiki/Roswell_incident][Roswell]], post [[https://en.wikipedia.org/wiki/Jekyll_Island][Jekyll Island]], pre [[https://en.wikipedia.org/wiki/October_Revolution][October Revolution]], in time with [[https://en.wikipedia.org/wiki/Freemasonry][masonry]] and the [[https://en.wikipedia.org/wiki/The_Buddha][buddha]].
    - 33rd rites, or jhanas, what do we want?


----------

#+begin_quote
"We shall have World Government, whether or not we like it. The only question is whether World Government will be achieved by conquest or consent."
#+end_quote
- Paul Warburg, to the Senate, 1950.



-------------

#+begin_quote
...just as the British government became
a powerful instrument in the Network’s toolbox, the United States offered an even greater
opportunity. By seizing control of US foreign policy, the Network could now access the
untapped military, economic, and political resources of America. It could use those resources to
continue what’s best described as its sovereignty destruction project. As an added bonus, it could
chain the political consequences and inescapable debt to the United States. And that’s exactly
what it has done.

For instance, since it was founded in 1947, the CIA (a creation of the Network)[5] has been used
to destabilize and topple dozens of uncooperative nations covertly[6] while the US military
(controlled by “policy makers” that are dominated by the Network) has been used to topple
dozens directly. Again, the costs and blowback accrue to the United States; the benefits go to the
Network. True, the United States does enjoy the “benefit” of appearing supremely powerful, but
this is only a cruel joke. When the Network is satisfied that all major obstacles to its unelected
rule have been removed, it will be a simple matter to destroy the US dollar, “justifiably” cut off
the flow of money and credit to the United States, and create the political incentive (necessity)
for the United States to fully enter the new global system.

Obviously, none of the Network’s actions to this point (and none of its future plans) would have
been possible without first seizing the levers of power in the United States
#+end_quote
- Tragedy and Hope 101


#+begin_quote
Phillip Dru: Administrator was written by none other than
Edward Mandell House himself.[11] In the book, House argues that dictatorship is necessary
because the rich and powerful have taken control, and they’re using their power against the poor
and less fortunate. To understand how shamefully cynical this is, consider the fact that House’s
propaganda was meant to strengthen, not weaken, the same “rich and powerful” individuals that
his book condemned.

Side Note: This is one of the most common tactics employed by the Network for manipulating
public opinion. It will point to an injustice (often caused by the Network itself), whip up an
emotional firestorm, and, at the peak of hysteria, offer a solution that furthers its own agenda.
Maybe this is why House published his novel anonymously. It would be pretty hard to hook
readers with his fight the elite storyline if they knew the author was “one of the first
‘kingmakers’ in modern American politics.”[12] In any event, the book is worth reading, not for
its entertainment value (it isn’t well written), but because it’s a short read that provides many
insights into how easily a handful of men can manipulate a democratic system of government
#+end_quote
- Tragedy and Hope 101


#+begin_quote
But of all the kings that House managed to
“make,” none paid better dividends than Woodrow Wilson.
Carefully selected and manipulated, House used Wilson to create the two essential funding
mechanisms for the Network’s “revolutionary adjustment” of US society. More specifically:
prior to the election of Woodrow Wilson, the Network did not possess the power to tax US
citizens’ income or control the nation’s money supply. Wilson signed both of these powers into
existence shortly after he took office. More than anything, this enabled House and the Network
to turn the United States away from sovereignty and toward servitude.
#+end_quote
- Tragedy and Hope 101


#+begin_quote
In an address he gave as president (July 4, 1914), Wilson proclaimed that
the role of the United States was to be “the light which shall shine unto all generations and guide
the feet of mankind to the goal of justice and liberty and peace.”[23] And to achieve this, Wilson generously pledged “every dollar” of America’s wealth, “every drop of her blood,” and all the
“energy of her people.”[24]
Even Henry Kissinger took aim at Wilson’s “conceit”:
In Wilson’s view, there was no essential difference between freedom for America and freedom
for the world…he developed an extraordinary interpretation of what George Washington had
really meant when he warned against foreign entanglements. Wilson redefined “foreign” in a
way that would surely have astonished the first president. What Washington meant, according to
Wilson, was that America must avoid becoming entangled in the purposes of others. But, Wilson
argued, nothing that concerns humanity “can be foreign or indifferent to us.” Hence America had
an unlimited charter to involve itself abroad…what extraordinary conceit to derive a charter for
global intervention from a Founding Father’s injunction against foreign entanglements, and to
elaborate a philosophy of neutrality that made involvement in war inevitable!
Wilson’s desire to create a global power structure that “no nation” or “probable combination of
nations” could resist,[26] coupled with his messiah complex, provided the perfect psychological
ingredients for turning the man into a useful idiot.
#+end_quote
- Tragedy and Hope 101


#+begin_quote
In short: without the Network’s backing, a candidate will remain a relative nobody in the
election. They will be relegated to begging door to door for enough money to run an (almost
meaningless) advertising campaign. However, with Network backing, the candidate can count on
millions of dollars in campaign donations, a long list of credible endorsements, and a nearly
priceless amount of exposure through the Network’s propaganda instruments. (In the unlikely
event that a truly independent candidate emerges, with enough money or a large enough
following to gain some ground, the Network will simply use its instruments to smear and
ostracize the candidate and the candidate’s supporters.)
#+end_quote
- Tragedy and Hope 101


#+begin_quote
The candidates might even genuinely disagree with a few
positions held by their opponents. In fact, it’s even better if they do. (The meaningless bickering
between them, and the partisan hysteria it incites among the public, only adds to the overall
illusion of voter choice.) But on the issues that matter most to the Network, each sponsored
candidate is virtually identical in value.
The beauty of this system is its simplicity. The Network scouts potential talent, performs the
necessary background checks, and, after conveying its expectations, offers its vital assistance to a
handful of candidates. After some “bombast, glitter, and speeches,” the public chooses from the
products (party, candidate, and platform) that were put before them.
#+end_quote
- Tragedy and Hope 101
