* What FifthXenia is.
- FifthXenia is a non-profit, that focuses on developing solutions that benefit humanity. 
  - We build systems that buttress decentralization over centralization, non-violent cooperation over violent force, transparency over secrecy, truth and honesty over lies and deception, encryption and anonymity over big brother, sound economics, spines over spineless, simplicitly and just enough over heedless extraneous addiction, and liberty over death.
  - (leading from the front, just people, same rules and principles applying to everyone) A society of autonomous individuals lifting those beneath them and building up, rather than  (leading from the back, ruler not same as ruled, lies, special privileges) top down stagnated slavery trauma poison.


#+begin_quote
An invisible empire has been set up above the forms of democracy.

Since I entered politics, I have chiefly had men’s views confided to me privately. Some of the biggest men in the United States, in the field of commerce and manufacture, are afraid of somebody, are afraid of something. They know that there is a power somewhere so organized, so subtle, so watchful, so interlocked, so complete, so pervasive, that they had better not speak above their breath when they speak in condemnation of it.

...[the] middle class is being more and more squeezed out by the processes which we have been taught to call processes of prosperity. Its members are sharing prosperity, no doubt; but what alarms me is that they are not originating prosperity. No country can afford to have its prosperity originated by a small controlling class. 


All over the Union people are coming to feel that they have no control over the course of affairs.

Men said: “We vote; we are offered the platform we want; we elect the men who stand on that platform, and we get absolutely nothing.” So they began to ask: “What is the use of voting? We know that the machines of both parties are subsidized by the same persons, and therefore it is useless to turn in either direction.”
#+end_quote
- President Woodrow Wilson, Excerpts from [[https://teachingamericanhistory.org/document/the-new-freedom][The New Freedom]], 1913
  - Pre-[[https://en.wikipedia.org/wiki/Transistor][transistor]] and digital age, radio, tv, pre the decision of the U.S to engage in [[https://en.wikipedia.org/wiki/Full-spectrum_dominance][full spectrum warfare]] post dieing down of the cold war, post [[https://en.wikipedia.org/wiki/Aurora,_Texas,_UFO_incident][Aurora]], pre [[https://en.wikipedia.org/wiki/Roswell_incident][Roswell]], post [[https://en.wikipedia.org/wiki/Jekyll_Island][Jekyll Island]], pre [[https://en.wikipedia.org/wiki/October_Revolution][October Revolution]], in time with [[https://en.wikipedia.org/wiki/Freemasonry][masonry]] and the [[https://en.wikipedia.org/wiki/The_Buddha][buddha]].
    - 33rd rites, or jhanas, what do we want?


#+begin_quote
"We shall have World Government, whether or not we like it. The only question is whether World Government will be achieved by conquest or consent."
#+end_quote
- Paul Warburg, to the Senate, 1950.


#+begin_quote
...just as the British government became
a powerful instrument in the Network’s toolbox, the United States offered an even greater
opportunity. By seizing control of US foreign policy, the Network could now access the
untapped military, economic, and political resources of America. It could use those resources to
continue what’s best described as its sovereignty destruction project. As an added bonus, it could
chain the political consequences and inescapable debt to the United States. And that’s exactly
what it has done.

For instance, since it was founded in 1947, the CIA (a creation of the Network)[5] has been used
to destabilize and topple dozens of uncooperative nations covertly[6] while the US military
(controlled by “policy makers” that are dominated by the Network) has been used to topple
dozens directly. Again, the costs and blowback accrue to the United States; the benefits go to the
Network. True, the United States does enjoy the “benefit” of appearing supremely powerful, but
this is only a cruel joke. When the Network is satisfied that all major obstacles to its unelected
rule have been removed, it will be a simple matter to destroy the US dollar, “justifiably” cut off
the flow of money and credit to the United States, and create the political incentive (necessity)
for the United States to fully enter the new global system.

Obviously, none of the Network’s actions to this point (and none of its future plans) would have
been possible without first seizing the levers of power in the United States
#+end_quote
- Tragedy and Hope 101
