* FifthXenia is:
- FifthXenia is a non-profit, that focuses on developing solutions that benefit humanity. 
  - We build systems that buttress decentralization over centralization, non-violent cooperation over violent force, transparency over secrecy, truth and honesty over lies and deception, encryption and anonymity over big brother, sound economics, spines over spineless, simplicitly and just enough over heedless extraneous addiction, and liberty over death.
  - (leading from the front, just people, same rules and principles applying to everyone) A society of autonomous individuals lifting those beneath them and building up, rather than  (leading from the back, ruler not same as ruled, lies, special privileges) top down stagnated slavery trauma poison.

* Our Three Guiding Principles:
- 1: ~Peoples World Order~ over ~New World Order~
- 2: ~Freedom of Action~ over ~Freedom of Speech not Reach~
  - (The era of speech has passed. We're entering the era of action.)
- 3: ~Social Eugenics~ over ~Propaganda, PsyOps, False Flags, Violence, Force, Subversion, Slavery, Trauma, Poison~

